name: Task2 workflows

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "Building application"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Testing application"
