name: Task3 workflows

on:
  push:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Show details
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
